config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'subscriptions/follow_tag'

  get 'subscriptions/unfollow_tag'

  devise_for :users
  
  get 'exchange_rate' => 'exchange_rate#index'
  get 'exchange_rate/convert' => 'exchange_rate#convert'

  resources :posts do
    resources :comments
  end

  root "posts#index"
  get 'results', to: 'results#index', as: 'results'

  get '/about' => 'pages#about', as: :about
  get '/alltags' => 'pages#alltags', as: :alltags
  get 'userposts/:id', to: 'posts#userposts', as: :userposts
  get 'tags/:tag', to: 'posts#withtag', as: :tag
  resources :users, only: [:show, :update, :edit]

  post '/follow_tag/:tag', to: 'subscriptions#follow_tag', as: :follow_tag
  post 'unfollow_tag/:tag', to: 'subscriptions#unfollow_tag', as: :unfollow_tag

  get '/myfeed', to: 'posts#userfeed', as: :myfeed
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    username_changed?
  end

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x500>", small: "90x90>" }
  # default_url: "missing_:style.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :username, uniqueness: { case_sensitive: true,
    message: "User with this name already exists." }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribed_tags, source: :tag, through: :subscriptions

  def follow(tag_id)
    subscriptions.create(tag_id: tag_id)
  end

  def unfollow(tag_id)
    subscriptions.find_by(tag_id: tag_id).destroy
  end

  def is_following(user_id, tag_id)
    is_sub = Subscription.find_by(user_id: user_id, tag_id: tag_id)
    if is_sub
      return true
    else
      return false
    end
  end

  def following_tag_list
    subscribed_tags.map(&:name)
  end

  def role?(requested_role)
    self.role == requested_role.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # load_and_authorize_resource
  def show
    if (User.find(params[:id]))
      @user = User.find(params[:id])
      if request.path != user_path(@user)
        redirect_to @user, status: :moved_permanently
      end
      @posts_counter = Post.where(user_id: @user.id).count
    else
      redirect_to root_path, notice: "User not found!"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

 private
  def user_params
    params.require(:user).permit(:information, :username, :avatar, :slug)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_name(user)
    if user.username.empty?
      "User" + user.id.to_s
    else
      user.username
    end
  end

  def subsribed_tags(user)
    user.subscribed_tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(' ')
  end
end

app/views/users/edit.html.erb
<h4>Edit Profile</h4>
<hr>
<div class="card">
  <div class="card-content">
    <%= form_for @user do |f| %>
      <div class="row">
        <div class="input-field col s12">
          <%= f.label :username %> <br>
          <%= f.text_field  :username %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :information %><br>
          <%= f.text_area :information, class: 'materialize-textarea', placeholder: "Type information about youself or your contacts" %>
        </div>
      </div>

      <p>
        <%= f.label :avatar %><br />
        <%= f.file_field :avatar %>
      </p>
      <br>
      <%= f.submit "Update", class: 'btn waves-effect waves-light btn deep-purple accent-2' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h4><strong><%= show_name(@user) %></strong></h4>

<hr>
<div class="card">
  <div class="col s12 m8 offset-m2 l6 offset-l3">
    <div class="card-panel grey lighten-5 z-depth-1">
      <div class="row valign-wrapper">
        <div class="col s1">
          <% if @user.avatar_file_size.nil? %>
            <i class="fa fa-linux fa-5x" aria-hidden="true"></i>
          <% else %>
            <%= image_tag @user.avatar.url(:small), class: "circle responsive-img" %>
          <% end %>
        </div>
        <div class="col s10">
          <span class="black-text">
            <p>
              Information:
              <% if @user.information.nil? || @user.information.empty? %>
                no information found.
              <% else %>
                <%= @user.information %>
              <% end %>
            </p>
            <p>
              <% if @posts_counter > 0 %>
                <%= @user.username.capitalize %> has typed
                <%= link_to "#{@posts_counter} questions.", userposts_path(@user.id) %>
              <% else %>
                <%= @user.username.capitalize %> has no questions
              <% end %>
            </p>
          </span>
        </div>
      </div>
      <div class="card-action">
        <p>
          <% if @user.subscribed_tags.empty? %>
            No subscriptions found
          <% else %>
            Subscribed on: <%= raw subsribed_tags(@user) %>
          <% end %>
        </p>
        <% if can? :update, @user  %>
          <%= link_to "Edit profile", edit_user_path, class: 'btn waves-effect waves-light btn deep-purple accent-2' %>
          <%= link_to "Change password", edit_user_registration_path, class: 'btn waves-effect waves-light btn deep-purple accent-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>