config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'subscriptions/follow_tag'

  get 'subscriptions/unfollow_tag'

  devise_for :users
  
  get 'exchange_rate' => 'exchange_rate#index'
  get 'exchange_rate/convert' => 'exchange_rate#convert'

  resources :posts do
    resources :comments
  end

  root "posts#index"
  get 'results', to: 'results#index', as: 'results'

  get '/about' => 'pages#about', as: :about
  get '/alltags' => 'pages#alltags', as: :alltags
  get 'userposts/:id', to: 'posts#userposts', as: :userposts
  get 'tags/:tag', to: 'posts#withtag', as: :tag
  resources :users, only: [:show, :update, :edit]

  post '/follow_tag/:tag', to: 'subscriptions#follow_tag', as: :follow_tag
  post 'unfollow_tag/:tag', to: 'subscriptions#unfollow_tag', as: :unfollow_tag

  get '/myfeed', to: 'posts#userfeed', as: :myfeed
end

app/views/shared/_footer.html.erb
<div id="footer">
  <footer class="page-footer blue lighten-2">
    <div class="footer-copyright">
      <div class="container">
        <%= link_to "About", about_path, class: 'grey-text text-lighten-4' %>
        <div class="grey-text text-lighten-4 right">
          Copyright © 2016 malworm | All rights reserved
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_header.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper blue lighten-2">
<!--       <div class="row brand-logo center hide-on-med-and-down">
        <form>
          <div class="input-field col s12">
            <input id="search" type="search" required placeholder="Search...">
            <label for="search"><i class="material-icons">search</i></label>
          </div>
        </form>
      </div> -->
      <ul id="slide-out" class="side-nav grey lighten-5">
        <br>
        <% if user_signed_in? %>
          <% if current_user.avatar_file_size.nil? %>
            <div style="text-align:center;" class="black-text">
              <i class="fa fa-linux fa-5x" aria-hidden="true"></i><br>
              <%= current_user.username %>
            </div>
          <% else %>
            <div style="text-align:center;" class="black-text">
              <%= image_tag current_user.avatar.url(:small), class: "circle responsive-img" %><br>
              <%= current_user.username %>
            </div>
          <% end %>
          <li><%= link_to "My Profile", user_path(current_user.id) %></li>
          <li><%= link_to "News Feed", myfeed_path %></li>
        <% else %>
          <div style="text-align:center;" class="black-text">
            <i class="fa fa-user fa-5x" aria-hidden="true"></i><br>
            Guest
          </div>
        <% end %>
        <li><%= link_to "All Questions", root_path %></li>
        <li><%= link_to "All Tags", alltags_path %></li>
        <li><%= link_to "Convert Currency", exchange_rate_path %></li>
  <!--  <li class="no-padding">
          <ul class="collapsible collapsible-accordion">
            <li>
              <a class="collapsible-header">Dropdown<i class="mdi-navigation-arrow-drop-down"></i></a>
              <div class="collapsible-body">
                <ul>
                  <li><a href="#!">First</a></li>
                  <li><a href="#!">Second</a></li>
                  <li><a href="#!">Third</a></li>
                  <li><a href="#!">Fourth</a></li>
                </ul>
              </div>
            </li>
          </ul>
        </li> -->
      </ul>
      <a href="#" data-activates="slide-out" class="button-collapse show-on-large">
        <i class="mdi-navigation-menu"></i>
      </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li>
            <%= link_to '<i class="left material-icons">power_settings_new</i>Log out'.html_safe,
            destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to '<i class="left material-icons">power_settings_new</i>Log in'.html_safe,
            new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

<script>
  $(document).ready(function(){
    // Initialize collapse button
    $(".button-collapse").sideNav({
      menuWidth: 225, // Default is 240
      edge: 'left', // Choose the horizontal origin
      closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
    });
    // Initialize collapsible (uncomment the line below if you use the dropdown variation)
    //$('.collapsible').collapsible();
  });
</script>