config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'subscriptions/follow_tag'

  get 'subscriptions/unfollow_tag'

  devise_for :users
  
  get 'exchange_rate' => 'exchange_rate#index'
  get 'exchange_rate/convert' => 'exchange_rate#convert'

  resources :posts do
    resources :comments
  end

  root "posts#index"
  get 'results', to: 'results#index', as: 'results'

  get '/about' => 'pages#about', as: :about
  get '/alltags' => 'pages#alltags', as: :alltags
  get 'userposts/:id', to: 'posts#userposts', as: :userposts
  get 'tags/:tag', to: 'posts#withtag', as: :tag
  resources :users, only: [:show, :update, :edit]

  post '/follow_tag/:tag', to: 'subscriptions#follow_tag', as: :follow_tag
  post 'unfollow_tag/:tag', to: 'subscriptions#unfollow_tag', as: :unfollow_tag

  get '/myfeed', to: 'posts#userfeed', as: :myfeed
end

app/views/pages/about.html.erb
<h4>About</h4>
<hr>
<ul class="collapsible" data-collapsible="accordion">
  <li>
    <div class="collapsible-header">
      <i class="fa fa-exclamation" aria-hidden="true"></i>Rules
    </div>
    <div class="collapsible-body">
      <p>
        Here is no special rules, you just have to be tolerant to other users. <br>
        Don't ask questions answers to which are plased in top google search results.
      </p>
    </div>
  </li>
  <li>
    <div class="collapsible-header">
      <i class="fa fa-info" aria-hidden="true"></i>About Site
    </div>
    <div class="collapsible-body">
      <p>
        This is open source Education-Project. <br>
        I wanted to create some place where people could find answers on
        their questions and to share knowledge. <br>
        <a href="https://github.com/malworm/Blog">
          <i class="fa fa-github fa-lg" aria-hidden="true"></i> source code
        </a>
      </p>
    </div>
  </li>
  <li>
    <div class="collapsible-header">
      <i class="fa fa-smile-o" aria-hidden="true"></i>About Me
    </div>
    <div class="collapsible-body">
      <p>
        I'm young programmer. You can call me malworm. <br>
        I like Ruby and Rails
        <i class="fa fa-diamond" aria-hidden="true"></i>
        and also this penguin
        <i class="fa fa-linux" aria-hidden="true"></i> <br>
        My dream is to develop some project, that could be useful for
        many people and write my name into the history.
      </p>
    </div>
  </li>
  <li>
    <div class="collapsible-header">
      <i class="fa fa-envelope-o" aria-hidden="true"></i>Contact
    </div>
    <div class="collapsible-body">
      <p>
        If you like what I do and want to work or to
        communicate with me, contact me via
        <a href="mailto:malworm@tutanota.com">
          <i class="fa fa-envelope-o" aria-hidden="true"></i> Email
        </a> <br>
        You can also check out some of my projects on
        <a href="https://github.com/malworm">
          <i class="fa fa-github fa-lg" aria-hidden="true"></i> github
        </a>
      </p>
    </div>
  </li>
</ul>

<script>
  $('.collapsible').collapsible({ accordion : false });
</script>

app/views/pages/alltags.html.erb
<h4>All Tags</h4>
<hr>
<% @tags.each do |tag| %>
  <div class="col-md-4 text-center">
        <div class="col s12 m7">
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                <i class="fa fa-tag" aria-hidden="true"></i>
                <%= tag.name %>
              </span>
              <br>
              <%= link_to "#{pluralize(tag.posts.size, "question")}", tag_path(tag.name)%>
            </div>
            <div class="card-action">
               <% if user_signed_in? %>
                <% if current_user.is_following(current_user.id, tag.id) %>
                  <%= button_to "Unfollow", unfollow_tag_path(tag.name),
                  method: :post, class: 'btn waves-effect waves-light btn deep-purple accent-2' %>
                <% else %>
                  <%= button_to "Follow", follow_tag_path(tag.name),
                  method: :post, class: 'btn waves-effect waves-light btn deep-purple accent-2' %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
  </div>
<% end %>

<% if user_signed_in? %>
  <div class="fixed-action-btn horizontal add_button">
    <%= link_to new_post_path, class: 'btn-floating btn-large deep-purple accent-2' do %>
      <i class="large material-icons">mode_edit</i>
    <% end %>
  </div>
<% end %>