config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'subscriptions/follow_tag'

  get 'subscriptions/unfollow_tag'

  devise_for :users
  
  get 'exchange_rate' => 'exchange_rate#index'
  get 'exchange_rate/convert' => 'exchange_rate#convert'

  resources :posts do
    resources :comments
  end

  root "posts#index"
  get 'results', to: 'results#index', as: 'results'

  get '/about' => 'pages#about', as: :about
  get '/alltags' => 'pages#alltags', as: :alltags
  get 'userposts/:id', to: 'posts#userposts', as: :userposts
  get 'tags/:tag', to: 'posts#withtag', as: :tag
  resources :users, only: [:show, :update, :edit]

  post '/follow_tag/:tag', to: 'subscriptions#follow_tag', as: :follow_tag
  post 'unfollow_tag/:tag', to: 'subscriptions#unfollow_tag', as: :unfollow_tag

  get '/myfeed', to: 'posts#userfeed', as: :myfeed
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  has_attached_file :image, styles: { large: "600x600>", medium: "350x350>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :title, presence: true, length: { minimum: 5, maximum: 60 }
  validates :body, presence: true
  validates :tags, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
    joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  include PgSearch
  pg_search_scope :search_everywhere, against: [:title],
  associated_against: { tags: [:name], user: [:username] }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :userposts, :withtag]
  load_and_authorize_resource except: [:userposts, :withtag, :userfeed]

  def index
    @posts = Post.order('created_at DESC').page(params[:page]).per(12)
  end

  def show
    @post = Post.find(params[:id])
    if request.path != post_path(@post)
      redirect_to @post, status: :moved_permanently
    end
    @postCreator = User.find(@post.user_id)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  def withtag
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).order('created_at DESC').page(params[:page]).per(12)
      @tagname = params[:tag]
      @tag = Tag.find_by_name(params[:tag])
    end
  end

  def userfeed
    idArr = Array.new
    allPosts = Post.order('created_at DESC')
    userTags = current_user.subscribed_tags.map(&:id)
    allPosts.each do |post|
      post.tags.map(&:id).any? do |t|
        idArr.push(post.id) if userTags.include?(t)
      end
    end
    @posts = Post.where(id: idArr).order('created_at DESC').page(params[:page]).per(12)
  end

  def userposts
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).order('created_at DESC').page(params[:page]).per(12)
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :image, :tag_list, :slug)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tags_size_valdiator(tagsSize)
   result = "+ "
   if (tagsSize - 1) > 0
    result += (tagsSize - 1).to_s + " more"
    result
   end
  end

  def tags_list(post)
    post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(' ')
  end
end

app/views/posts/_editform.html.erb
<div class="card">
  <div class="card-content">
    <%= form_for @post, html: { multipart: true } do |f| %>

      <% if @post.errors.any? %>
        <ul class="collapsible red lighten-4" data-collapsible="accordion">
          <li>
            <div class="collapsible-header red lighten-4">
              <i class="material-icons">error_outline</i>
              <%= pluralize(@post.errors.count, "error") %>
            </div>

            <div class="collapsible-body">
                <% @post.errors.full_messages.each do |msg| %>
                  <p><%= msg %></p>
                <% end %>
            </div>
          </li>
        </ul>
      <% end %>

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :title %> <br>
          <%= f.text_field  :title %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
        <%= f.label :tag_list, "Tags (separated by commas)" %><br />
        <%= f.text_field :tag_list %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :body %><br>
          <%= f.text_area :body, class: 'materialize-textarea' %>
        </div>
      </div>

      <%= f.submit "Update", class: 'btn btn waves-effect waves-light btn deep-purple accent-2' %>

      <!-- <div class="fixed-action-btn horizontal click-to-toggle add_button">
        <a class="btn-floating btn-large deep-purple accent-2">
          <i class="large material-icons">add</i>
        </a>
        <ul>
          <li>
          <a class="btn-floating blue">
          <i class="material-icons">add_a_photo</i></a>
          </li>
        </ul>
      </div> -->

    <% end %>
  </div>
</div>

<script>
  $('.collapsible').collapsible({ accordion : false });
</script>

app/views/posts/_form.html.erb
<div class="card">
  <div class="card-content">
    <%= form_for @post, html: { multipart: true } do |f| %>

      <% if @post.errors.any? %>
        <ul class="collapsible red lighten-4" data-collapsible="accordion">
          <li>
            <div class="collapsible-header red lighten-4">
              <i class="material-icons">error_outline</i>
              <%= pluralize(@post.errors.count, "error") %>
            </div>

            <div class="collapsible-body">
                <% @post.errors.full_messages.each do |msg| %>
                  <p><%= msg %></p>
                <% end %>
            </div>
          </li>
        </ul>
      <% end %>

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :title %> <br>
          <%= f.text_field  :title %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
        <%= f.label :tag_list, "Tags (separated by commas)" %><br />
        <%= f.text_field :tag_list %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :body %><br>
          <%= f.text_area :body, class: 'materialize-textarea' %>
        </div>
      </div>

      <%= f.submit "Create", class: 'btn btn waves-effect waves-light btn deep-purple accent-2' %>

     <!--  <div class="fixed-action-btn horizontal click-to-toggle add_button">
        <a class="btn-floating btn-large deep-purple accent-2">
          <i class="large material-icons">add</i>
        </a>
        <ul>
          <li>
          <a class="btn-floating blue">
          <i class="material-icons">add_a_photo</i></a>
          </li>
        </ul>
      </div> -->
    <% end %>
  </div>
</div>

<script>
  $('.collapsible').collapsible({ accordion : false });
</script>

app/views/posts/_mainpage.html.erb
<% @posts.each do |post| %>
  <div class="col-md-4 text-center">
        <div class="col s12 m7">
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                <%= link_to excerpt(post.title, post.title[0], radius: 16), post_path(post) %>
              </span>
              <p><%= post.created_at.strftime(" %B, %d, %Y") %></p>
            </div>
            <div class="card-action">
               <p>
                <i class="fa fa-tags" aria-hidden="true"></i>
                <%= link_to post.tags.first.name, tag_path(post.tags.first.name) %>
                <%= tags_size_valdiator(post.tags.map.size) %>
              </p>
            </div>
          </div>
        </div>
  </div>
<% end %>

<% if user_signed_in? %>
  <div class="fixed-action-btn horizontal add_button">
    <%= link_to new_post_path, class: 'btn-floating btn-large deep-purple accent-2 ' do %>
      <i class="large material-icons">mode_edit</i>
    <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h4>Edit Post</h4>
<% if can? :update, @post %>
  <%= render 'editform' %>
<% end %>

app/views/posts/index.html.erb
<h4>All Questions</h4>
<hr>
<%= render 'mainpage' %>

<div class="row">
  <div class="col s12">
    <br><br><br>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<h4>New Question</h4>
<hr>
<%= render 'form' %>

app/views/posts/show.html.erb
<h4>
  <%= link_to @postCreator.username, user_path(@postCreator.id) %>
</h4>
<hr>
<div class="card">
  <% if @post.image.file? %>
    <div class="card-image">
      <%= image_tag @post.image.url(:medium) %>
    </div>
  <% end %>

  <div class="card-content">
    <span class="card-title grey-text text-darken-4"><%= @post.title %></span>
    <p><%= @post.body %></p>
  </div>
  <div class="card-action">
    <p>
      <i class="fa fa-tags" aria-hidden="true"></i>
      <%= raw tags_list(@post) %>
    </p>
    <% if can? :update, @post %>
      <%= link_to '<i class="material-icons left">mode_edit</i>edit'.html_safe, edit_post_path(@post),
      class: 'btn waves-effect waves-light btn deep-purple accent-2' %>
    <% end %>
    <% if can? :destroy, @post %>
      <%= link_to '<i class="material-icons left">delete</i>delete'.html_safe, post_path(@post), class: 'btn waves-effect waves-light btn deep-purple accent-2', method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
  </div>

  <% if @post.comments.any? %>
  <br>
    <ul class="collapsible" data-collapsible="accordion">
      <li>
        <div class="collapsible-header">
          <i class="material-icons">comment</i>
          <%= pluralize(@post.comments.size, "comment") %>
          <i class="material-icons right">keyboard_arrow_down</i>
        </div>
        <div class="collapsible-body">
          <div class="col s12 m8 offset-m2 l6 offset-l3">
            <div class="card-panel grey lighten-5 z-depth-1">
              <%= render @post.comments.order(:is_answer).reverse_order %>
            </div>
          </div>
        </div>
      </li>
    </ul>
  <% else %>
    <br>
    <!-- <h4>No Comments</h4> -->
    <ul class="collapsible" data-collapsible="accordion">
      <li>
        <div class="collapsible-header">
          <i class="material-icons">comment</i>
          No comments
        </div>
      </li>
    </ul>
  <% end %>
</div>



<hr/>
<% if user_signed_in? %>
  <br>
  <h4>Add a comment:</h4>
  <%= render "comments/form" %>
<% else %>
  <%= link_to "Log in", new_user_session_path,
  class: 'btn waves-effect waves-light btn deep-purple accent-2'%>
<% end %>

<script>
  $('.collapsible').collapsible({ accordion : false });
</script>

app/views/posts/userfeed.html.erb
<h4>News Feed</h4>
<hr>
<% if @posts.empty? %>
  <h4>Subscribe on some Tags to have own feed</h4>
  <% if user_signed_in? %>
    <div class="fixed-action-btn horizontal add_button">
      <%= link_to new_post_path, class: 'btn-floating btn-large deep-purple accent-2' do %>
        <i class="large material-icons">mode_edit</i>
      <% end %>
    </div>
  <% end %>
<% else %>
  <%= render 'mainpage' %>
  <div class="row">
    <div class="col s12">
      <br><br><br>
      <%= paginate @posts %>
    </div>
  </div>
<% end %>

app/views/posts/userposts.html.erb
<h4>
  <%= @posts[0].user.username %> questions:
</h4>
<hr>
<%= render 'mainpage' %>
<div class="row">
  <div class="col s12">
    <br><br><br>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/withtag.html.erb
<h4>
  <i class="fa fa-tag" aria-hidden="true"></i>
  <%= @tagname %>
</h4>
<br>
<% if user_signed_in? %>
  <% if current_user.is_following(current_user.id, @tag.id) %>
    <%= button_to "Unfollow", unfollow_tag_path(@tagname), method: :post, class: 'btn waves-effect waves-light btn deep-purple accent-2' %>
  <% else %>
    <%= button_to "Follow", follow_tag_path(@tagname), method: :post, class: 'btn waves-effect waves-light btn deep-purple accent-2' %>
  <% end %>
<% end %>
<hr>

<%= render 'mainpage' %>

<div class="row">
  <div class="col s12">
    <br><br><br>
    <%= paginate @posts %>
  </div>
</div>